[package]
name = "cyclops-r"
version = "0.1.0"
authors = ["KaOs1 <kaos1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.11"
flexi_logger = "0.16.1"
imgui = "0.5.0"
glium = "0.27.0"
